version: 2.1
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
      - run:
          command: pip install -r requirements_dev.txt
      - run:
          command: pip install -e .
      - run:
          command: python -m mypy tools/
      - run:
          command: python -m mypy tests/
      - run:
          command: python -m mypy src/malti/
      - run:
          command: python -m pylint tools/
      - run:
          command: python -m pylint tests/
      - run:
          command: python -m pylint src/malti/
      - run:
          command: python tools/validate_project.py
      - run:
          command: cd docs; make html; cd ..
      - run:
          command: cd tests; python -m unittest; cd ..

workflows:
  build-and-test:
    jobs:
      - test-python
